name: Release-it

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: release-it
        run: |
          mv package.json tmp.package.json
          bun install @release-it/conventional-changelog
          mv tmp.package.json package.json 
          bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
